// const productRedirects = [
//     { source: '/productdetail.php?categ=K11&idproduct=69', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K11&idproduct=26', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K11&idproduct=70', destination: '/products/lg-10385-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=33', destination: '/products/lg-1077-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=29', destination: '/products/lg-1095-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=30', destination: '/products/lg-1096-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=48', destination: '/products/lg-1098-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=35', destination: '/products/lg-1238-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=71', destination: '/products/lg-12385-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=72', destination: '/products/lg-12386-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=43', destination: '/products/lg-1277-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=44', destination: '/products/lg-1292-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=36', destination: '/products/lg-1295-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=38', destination: '/products/lg-1296-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=40', destination: '/products/lg-1298-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=87', destination: '/products/lg-1299-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=45', destination: '/products/lg-1596-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=23', destination: '/products/lg-638-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=22', destination: '/products/lg-696-2' },
//     { source: '/productdetail.php?categ=K11&idproduct=25', destination: '/products/lg-838-2-mk1' },
//     { source: '/productdetail.php?categ=K11&idproduct=24', destination: '/products/lg-896-2' },
//     { source: '/productdetail.php?categ=K17&idproduct=73', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K18&idproduct=79', destination: '/products/lg-6521' },
//     { source: '/productdetail.php?categ=K12&idproduct=51', destination: '/products/pg-1054-2-red' },
//     { source: '/productdetail.php?categ=K12&idproduct=52', destination: '/products/pg-1254-2-red' },
//     { source: '/productdetail.php?categ=K12&idproduct=50', destination: '/products/pg-854-2-red' },
//     { source: '/productdetail.php?categ=K13&idproduct=54', destination: '/products/w-8347-b' },
//     { source: '/productdetail.php?categ=K13&idproduct=53', destination: '/products/w-8347-k' },
//     { source: '/productdetail.php?categ=K14&idproduct=77', destination: '/products/bst-422-mk3' },
//     { source: '/productdetail.php?categ=K14&idproduct=78', destination: '/products/bst-522-mk3' },
//     { source: '/productdetail.php?categ=K14&idproduct=58', destination: '/products/bst-1614' },
//     { source: '/productdetail.php?categ=K14&idproduct=76', destination: '/products/bst-615-mk3' },
//     { source: '/productdetail.php?categ=K14&idproduct=60', destination: '/products/bst-6981-mk1' },
//     { source: '/productdetail.php?categ=K15&idproduct=63', destination: '/products/pg-298' },
//     { source: '/productdetail.php?categ=K22&idproduct=85', destination: '/products/bst-1023-dual' },
//     { source: '/productdetail.php?categ=K21&idproduct=88', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K21&idproduct=83', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K21&idproduct=89', destination: '/drivers' },
//     { source: '/productdetail.php?categ=K21&idproduct=84', destination: '/drivers' },
//     { source: '/productdetail.php', destination: '/drivers' },
//     { source: '/products.php?categ=K11', destination: '/drivers/legacy/subwoofer' },
//     { source: '/products.php?categ=K17', destination: '/drivers' },
//     { source: '/products.php?categ=K18', destination: '/drivers/legacy/coaxial' },
//     { source: '/products.php?categ=K19', destination: '/drivers' },
//     { source: '/products.php?categ=K12', destination: '/drivers/prestige/subwoofer' },
//     { source: '/products.php?categ=K13', destination: '/drivers/prestige/woofer' },
//     { source: '/products.php?categ=K14', destination: '/drivers/prestige/full-range' },
//     { source: '/products.php?categ=K15', destination: '/drivers/prestige/tweeter' },
//     { source: '/products.php?categ=K22', destination: '/drivers/prestige/coaxial' },
//     { source: '/products.php?categ=K8', destination: '/drivers' },
//     { source: '/products.php', destination: '/drivers' },
//     { source: '/index.php', destination: '/' },
//     { source: '/aboutus.php', destination: '/about-us' },
//     { source: '/links.php', destination: '/' },
//     { source: '/capabilities.php', destination: '/' },
//     { source: '/news.php', destination: '/news' },
//     { source: '/events.php', destination: '/' },
//     { source: '/distributors.php', destination: '/distributors' },
//     { source: '/contact.php', destination: '/contact' },
//   ]
  
  module.exports = [
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '69' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '26' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '70' },
      ],
      destination: '/products/lg-10385-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '33' },
      ],
      destination: '/products/lg-1077-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '29' },
      ],
      destination: '/products/lg-1095-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '30' },
      ],
      destination: '/products/lg-1096-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '48' },
      ],
      destination: '/products/lg-1098-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '35' },
      ],
      destination: '/products/lg-1238-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '71' },
      ],
      destination: '/products/lg-12385-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '72' },
      ],
      destination: '/products/lg-12386-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '43' },
      ],
      destination: '/products/lg-1277-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '44' },
      ],
      destination: '/products/lg-1292-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '36' },
      ],
      destination: '/products/lg-1295-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '38' },
      ],
      destination: '/products/lg-1296-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '40' },
      ],
      destination: '/products/lg-1298-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '87' },
      ],
      destination: '/products/lg-1299-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '45' },
      ],
      destination: '/products/lg-1596-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '23' },
      ],
      destination: '/products/lg-638-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '22' },
      ],
      destination: '/products/lg-696-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '25' },
      ],
      destination: '/products/lg-838-2-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K11' },
        { type: 'query', key: 'idproduct', value: '24' },
      ],
      destination: '/products/lg-896-2',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K17' },
        { type: 'query', key: 'idproduct', value: '73' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K18' },
        { type: 'query', key: 'idproduct', value: '79' },
      ],
      destination: '/products/lg-6521',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K12' },
        { type: 'query', key: 'idproduct', value: '51' },
      ],
      destination: '/products/pg-1054-2-red',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K12' },
        { type: 'query', key: 'idproduct', value: '52' },
      ],
      destination: '/products/pg-1254-2-red',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K12' },
        { type: 'query', key: 'idproduct', value: '50' },
      ],
      destination: '/products/pg-854-2-red',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K13' },
        { type: 'query', key: 'idproduct', value: '54' },
      ],
      destination: '/products/w-8347-b',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K13' },
        { type: 'query', key: 'idproduct', value: '53' },
      ],
      destination: '/products/w-8347-k',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K14' },
        { type: 'query', key: 'idproduct', value: '77' },
      ],
      destination: '/products/bst-422-mk3',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K14' },
        { type: 'query', key: 'idproduct', value: '78' },
      ],
      destination: '/products/bst-522-mk3',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K14' },
        { type: 'query', key: 'idproduct', value: '58' },
      ],
      destination: '/products/bst-1614',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K14' },
        { type: 'query', key: 'idproduct', value: '76' },
      ],
      destination: '/products/bst-615-mk3',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K14' },
        { type: 'query', key: 'idproduct', value: '60' },
      ],
      destination: '/products/bst-6981-mk1',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K15' },
        { type: 'query', key: 'idproduct', value: '63' },
      ],
      destination: '/products/pg-298',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K22' },
        { type: 'query', key: 'idproduct', value: '85' },
      ],
      destination: '/products/bst-1023-dual',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K21' },
        { type: 'query', key: 'idproduct', value: '88' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K21' },
        { type: 'query', key: 'idproduct', value: '83' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K21' },
        { type: 'query', key: 'idproduct', value: '89' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      has: [
        { type: 'query', key: 'categ', value: 'K21' },
        { type: 'query', key: 'idproduct', value: '84' },
      ],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/productdetail.php',
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K11' }],
      destination: '/drivers/legacy/subwoofer',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K17' }],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K18' }],
      destination: '/drivers/legacy/coaxial',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K19' }],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K12' }],
      destination: '/drivers/prestige/subwoofer',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K13' }],
      destination: '/drivers/prestige/woofer',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K14' }],
      destination: '/drivers/prestige/full-range',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K15' }],
      destination: '/drivers/prestige/tweeter',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K22' }],
      destination: '/drivers/prestige/coaxial',
      permanent: true,
    },
    {
      source: '/products.php',
      has: [{ type: 'query', key: 'categ', value: 'K8' }],
      destination: '/drivers',
      permanent: true,
    },
    {
      source: '/products.php',
      destination: '/drivers',
      permanent: true,
    },
    { source: '/index.php', destination: '/', permanent: true },
    { source: '/aboutus.php', destination: '/about-us', permanent: true },
    { source: '/links.php', destination: '/', permanent: true },
    { source: '/capabilities.php', destination: '/', permanent: true },
    { source: '/news.php', destination: '/news', permanent: true },
    { source: '/events.php', destination: '/', permanent: true },
    { source: '/distributors.php', destination: '/distributors', permanent: true },
    { source: '/contact.php', destination: '/contact', permanent: true },
  ];